# Generated by Django 2.2.7 on 2019-11-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrent',
            name='book_tenants',
        ),
        migrations.AddField(
            model_name='booksrent',
            name='book_renter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p_library.Friend', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Author', verbose_name='Автор'),
        ),
    ]
